services:
  - type: web
    name: factos-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
      - key: DATABASE_URL
        fromDatabase:
          name: factos-postgres
          property: connectionString

databases:
  - name: factos-postgres
    databaseName: factos_db
    user: factos_user
    plan: free
