services:
  - type: web
    name: factos-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    disk:
      name: gastos-data
      mountPath: ./data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
